### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by retrixe** [retrixe/writer#5]
- [ ] Revamp the user interface.
- [ ] Unmount devices before writing to them (see if reserving them is possible).
- [ ] Add validation for written images.
- [ ] Improve custom dd performance.
- [ ] Create a proper README.
- [ ] E2E test on macOS and Linux.

Windows support will likely not be completed in time for 1.0 and will most likely be completed in 1.1 instead, but the basics are already there in any case.
